config/routes.rb
Rails.application.routes.draw do
  devise_for :accounts

  resources "conversations" do
    resources "messages"
  end


  get "/browse" => "browse#browse", as: :browse
  get "/matches" => "browse#matches", as: :matches
  post "/approve/:id" => "browse#approve", as: :approve_user
  post "/decline/:id" => "browse#decline", as: :decline_user
  post "get/conversation/:id" => "browse#open_conversation", as: :open_conversation

  root to: "public#home"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/account.rb
class Account < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many_attached :images

  def matches
    # gathering all ids of users that we like and like us in 2 arrays.
    liked_account_ids = Like.where(account_id: self.id).map(&:liked_account_id)
    puts liked_account_ids
    likes_me_account_ids = Like.where(liked_account_id: self.id).map(&:account_id)
    puts likes_me_account_ids
    # create a new array of matching liked ids.
    matched_ids = liked_account_ids.select{|id| likes_me_account_ids.include?(id)}
    puts matched_ids
    Account.where(id: matched_ids)
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  has_many :messages, dependent: :destroy
  accepts_nested_attributes_for :messages, allow_destroy: true

  validates_presence_of :sender_id, :recipient_id
  validates_uniqueness_of :sender_id, scope: :recipient_id

  scope :between, -> (sender_id, recipient_id ) do
    where("(sender_id = ? AND recipient_id = ?) OR (sender_id = ? AND recipient_id = ?)", sender_id, recipient_id, recipient_id, sender_id)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  validates_uniqueness_of :liked_account_id, scope: :account_id
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :conversation
  belongs_to :account

  validates_presence_of :body, :account_id
end

app/controllers/application_controller.rb
 class ApplicationController < ActionController::Base
  before_action :configure_devise, if: :devise_controller?

  private

  def configure_devise
    devise_parameter_sanitizer.permit(:account_update, keys: [ :first_name, :last_name, :username, images: [] ])
  end
end

app/controllers/browse_controller.rb
class BrowseController < ApplicationController

  def browse
    # browse only accounts that haven't been liked already
    liked_account_ids = Like.where(account_id: current_account.id).map(&:liked_account_id)
    liked_account_ids << current_account.id
    @users = Account.includes(:images_attachments).where.not(id: liked_account_ids)
    @matches = current_account.matches
  end

  def approve
    account_id = params[:id]
    # User likes User
    logger.debug "User id for matching is #{account_id}"
    # Create a like for user
    new_like = Like.new(liked_account_id: account_id)
    new_like.account_id = current_account.id

    if new_like.save
      existing_like = Like.where(account_id: account_id, liked_account_id: current_account.id).count
      @they_like_us = existing_like > 0
    else
    end
  end

  def decline
  end

  def open_conversation
    id = params[:id]
    @profile = Account.find(id)
    likes = Like.where(account_id: current_account.id, liked_account_id: id)
    @match = likes.first if likes.size > 0

    conversation = Conversation.between(id, current_account.id)

    @conversation = conversation.size > 0 ? conversation.first : Conversation.new
    @messages = @conversation.messages.includes(account: :images_attachments) if @conversation.persisted?
    @message = @conversation.messages.build

    if @profile.present?
      respond_to do |format|
        format.js {
          render "browse/conversation"
        }
      # get conversation entries for this user
      end
    end
  end
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController

  def create
    @conversation = Conversation.new(conversation_params)
    @conversation.sender_id = current_account.id
    @conversation.messages.first.account_id = current_account.id

    if @conversation.save!
      logger.debug "conversation has been saved."
    else
      logger.debug "unable to save conversation."
    end
  end

  def update
    @conversation = Conversation.find(params[:id])
    respond_to do |format|
      format.js {
        if @conversation.update!(conversation_params)
          @messages = @conversation.messages
          render "browse/conversation_messages"
        else

        end
      }
    end
  end

  private

  def conversation_params
    params.require(:conversation).permit(:recipient_id, messages_attributes: [:body, :account_id])
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  # def create

  # end

  # private

  # def conversation_params

  # end

end

app/controllers/public_controller.rb
class PublicController < ApplicationController

  def home
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/browse/_conversation.html.erb
  <div class="row">
    <div class="col-12 top-bar">
      <i class="fa fa-times fa-2x text-muted float-right" id="close-conversation"></i>
      <%= link_to image_tag(@profile.images.first, width: "40px", height: "40px", class: "float-left rounded-circle mr-3"), "#" %>
      <p class="text-muted mt-2">You matched with <%= @profile.first_name %> on <%= @match.created_at.strftime("%d/%m/%y") %>.</p>
    </div>
  </div>

  <div class="row">
    <div class="col-12 text-center">
      <% if @conversation.new_record? %>
        <div id="initiate-converation" class="text-center">
          <p class="mt-3">You matched with <span><%= @profile.first_name %></span> <%= time_ago_in_words @match.created_at %> ago.</p>
          <%= link_to image_tag(@profile.images.first, width: "200px", height: "200px", class: "rounded-circle mt-3 mb-5"), "#" %>

          <p>Send them a message.</p>
        </div>
      <% end %>

      <div id="conversation_messages"> <%= render partial: "browse/messages" unless @conversation.new_record? %></div>
    </div>
  </div>
  <div class="row">
    <div class="col-12 mt-5 botton-bar">
      <%= render partial: "browse/new_conversation" %>
    </div>
  </div>

app/views/browse/_matches.html.erb
<% @matches.each do |match| %>
  <div class="col-sm-4 mt-3">
    <% if match.images.attached? %>
    <div class="match-tile rounded" data-id="<%= match.id %>" style="background-image: url('<%= url_for match.images.first %>')">
      <p class="text-white"><%= match.first_name %></p>
    </div>
    <% end %>
  </div>
<% end %>

app/views/browse/_messages.html.erb
<% @messages.each do |message| %>
  <% if message.persisted? %>
  <div class="row mb-2">
      <div class="col-sm-2 col-lg-1 text-right">
        <%= image_tag message.account.images.first, class: "rounded-circle", width: "40px", height: "40px" if message.account.images.any? %>
      </div>
      <div class="col-sm-10 col-lg-11">
        <div class="float-left p-2 rounded conversation_message">
          <%= simple_format message.body %>
        </div>
    </div>
  </div>
  <% end %>
<% end %>

app/views/browse/_new_conversation.html.erb
<%= form_with model: @conversation do |form| %>
  <%= form.hidden_field :recipient_id, value: @profile.id %>

  <div class="input-group">
    <%= form.fields_for :messages, @message do |message_form| %>
    <%= message_form.hidden_field :account_id, value: current_account.id %>
    <%= message_form.text_field :body, placeholder: "Enter your message here", class: "form-control form-control-lg" %>
    <% end %>

    <div class="input-group-append">
      <input type="submit" name="submit" value="Send" class="btn btn-dark btn-lg pl-5 pr-5">
    </div>
  </div>
<% end %>

app/views/browse/browse.html.erb
<div class="row">
  <div class="col-md-3 bg-white border-right shadow-sm">
    <%= render "layouts/profile_bar" %>
    <!-- Banner for the left side profile bar -->


    <!--    These are the tabs for messages and matches. -->
    <ul class="nav nav-dating-sidebar ml-4 mt-3 mb-3" id="pills-tab" role="tablist">
      <li class="nav-item">
        <a class="nav-link" id="pills-home-tab" data-toggle="pill" href="#pills-home" role="tab" aria-controls="pills-home" aria-selected="true">Matches</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" id="pills-profile-tab" data-toggle="pill" href="#pills-messages" role="tab" aria-controls="pills-profile" aria-selected="false">Messages</a>
      </li>

    </ul>
    <div class="tab-content" id="pills-tabContent">
      <div class="tab-pane ml-2 fade" id="pills-home" role="tabpanel" aria-labelledby="pills-home-tab">
        <%= render "browse/matches" %>
      </div>
      <div class="tab-pane ml-2 fade" id="pills-messages" role="tabpanel" aria-labelledby="pills-profile-tab">
        <div class="col">
          <p>You have no messages yet.</p>
        </div>
      </div>
    </div>
  </div>
  <!-- This is the slideshow that shows potential matches. -->
  <div class="col-9 col-md-9">
    <ul id="slides">
      <% @users.each_with_index do |user, i| %>
        <li class="slide <%= 'showing' if i == 0 %>" data-id="<%= user.id %>">
          <div class="image-carousel" style="background-image: url('<%= url_for user.images.first %>')">
          </div>
          <div class="user-details">
            <span class="user-name"> <%= user.first_name %></span>, 31<br />
            <i class="fa fa-graduation-cap mr-1"></i> job/studies<br />
            <i class="fa fa-map-marker mr-2"></i> location
          </div>
        </li>
      <% end %>
    </ul>

    <div id="slide-controls">
      <span class="controls" id="decline"><i class="fa fa-times-circle fa-2x"></i></span>
      <span class="controls" id="approve"><i class="fa fa-heart fa-2x"></i></span>
    </div>
    <div id="conversation">
    </div>
  </div>
</div>

<!-- Here is where we show conversations with our matches. -->

app/views/browse/conversation.js.erb
$("#conversation").html("<%= escape_javascript(render partial: 'browse/conversation') %>").show();

// bind dom element for on click event
$("#close-conversation").on("click", function(){
  $("#conversation").hide();
});

app/views/browse/conversation_messages.js.erb
console.log('message has been saved.');
$("#initiate-converation").hide();
$("#conversation_messages").html("<%= escape_javascript(render partial: 'browse/messages') %>");

app/views/browse/matches.html.erb
<%= render "browse/matches" %>

app/views/layouts/_footer.html.erb
<footer class="footer border-top shadow-sm">
  <div class="container">
    <span class="text-black">Dating Robot © 2021.</span>
  </div>
</footer>

app/views/layouts/_nav.html.erb
<navbar class="navbar d-flex flex-column flex-md-row align-items-center p-3 px-md-4 border-bottom shadow-sm">
    <h5 class="my-0 mr-md-auto font-weight-normal">
      <%= link_to "Dating Robot", "/", class: "text-black mr-2" %>
    </h5>
    <% if account_signed_in? %>

      <nav class="my-2 my-md-0 mr-md-3">
        <%= link_to "Browse", browse_path, class: "text-black mr-2" %>
        <%= link_to "Settings", edit_account_registration_path, class: "text-black" %>

      </nav>

      <%= link_to "Sign Out", destroy_account_session_path, class: "text-black" %>


    <% else %>

      <nav class="my-2 my-md-0 mr-md-3">
        <a class="p-2 text-black" href="#">About Us</a>
        <%= link_to "Sign In", new_account_session_path, class: "p-2 text-black mr-2" %>
        <%= link_to "Sign Up", new_account_registration_path, class: "text-black" %>
      </nav>
    <% end %>
</navbar>

app/views/layouts/_profile_bar.html.erb
<div class="profile-bar bg-danger">
  <%= link_to "", class: "d-block text-white" do %>
    <%= link_to "My Profile", edit_account_registration_path, class: "my-profile mt-2 text-white"%>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dating Social</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application'%>
  </head>

  <body>
    <%= render "layouts/nav" %>

<!--       <p class="notice text-center"><%= notice %></p>
      <p class="alert text-center"><%= alert %></p> -->

      <div class="home">
        <%= yield %>
      </div>

    <%= render "layouts/footer" %>
  </body>
</html>